urls.py
import app.models.templates

from django.conf.urls import patterns, include
from django.conf.urls.static import static

from django.views.generic.edit import UpdateView
from django.contrib import auth, admin
from django.contrib.auth.decorators import login_required

from feincms.module.page.sitemap import PageSitemap

import settings

import app.models.templates
import app.models.user
import app.models.models
import app.models.event
from app.models.page import Page

import feincms.module.medialibrary.admin
import app.admin
import django.contrib.sites.admin

from app import views, mailinglists, forms, ical

urlpatterns = patterns('',
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^admin/', include(admin.site.urls)),

    (r'^(favicon\.ico|robots\.txt|apple-touch-icon\.png)\/?$', 
        'django.views.static.serve', {
            'document_root': settings.STATICFILES_DIRS[0],
    }),
    
    (r"^mailsender/$", mailinglists.mailsender),
                       
    (r"^ical(.php|.ics)?/$", ical.cal_events),
    
    (r'^users/login/$', 'django.contrib.auth.views.login', 
        dict(authentication_form=forms.LoginForm)),
    (r'^users/logout/$', login_required(auth.views.logout)),
    (r'^users/profile/$', views.is_active_required(
        lambda request: UpdateView.as_view(
            model=auth.models.User, form_class=forms.UserForm,
            success_url="/users/profile/")
        (request, pk=request.user.pk))),
                       
    (r'^event/signup/(?P<event_pk>\d+)$', views.is_active_required(
        views.EventSignup.as_view(success_url="/upcoming/"))),

    #(r'^sentry/', include('sentry.web.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', 
        {'sitemaps': {'pages': PageSitemap(
            queryset=Page.objects.filter(require_login=False,
                                         require_permission=False))}}),
    
    (r'', include('feincms.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
_urlpatterns = urlpatterns
def u():
    for _u in _urlpatterns:
        try:
            yield _u
        except TypeError as e:
            raise Exception(str(e))

urlpatterns = list(u())
"""

app/models/event.py
#coding: utf-8
import datetime

from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from model_utils.managers import InheritanceManager
from django.utils.translation import ugettext_lazy as _
from collections import OrderedDict

from ..ak import section_choices

class Event(models.Model):   
    date = models.DateField(_("date"))
    time_location = models.TimeField(_("time location"), blank=True, null=True)
    info = models.TextField(_("info"), blank=True)
    
    objects = InheritanceManager()
    
    last_modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    name = "Event"

    # assumes objects annotated
    def get_signup(self, user):
        try:
            return self.user_signup
        except AttributeError:
            try:
                return Signup.objects.get(user=user, event=self)
            except Signup.DoesNotExist:
                return None
    
    def get_coming(self):
        try:
            return self.num_coming
        except AttributeError:
            return self.signup_set.filter(coming__in=[Signup.HOLE, Signup.DIRECT]).count()

    def get_signed_up(self):
        try:
            return self.event_ptr.signup__count
        except AttributeError:
            return self.signup_set.count()
    
    class Meta:
        ordering = ["date"]
        verbose_name = _("event")
        verbose_name_plural = _('events')
        app_label = "app"
    
    def __str__(self):
        name = self.name
        if self.__class__ == Event:
            if hasattr(self, "_gig_cache") and self._gig_cache is not None:
                name = self.gig.name
            if hasattr(self, "_rehearsal_cache") and self._rehearsal_cache is not None:
                name = self.rehearsal.name
        return u"%s - %s" % (name, self.date)

class Rehearsal(Event):
    fika = models.CharField(_("fika"), max_length=2, choices=section_choices)
    
    location = models.CharField(_("location"), max_length=128, default=u"Hålan")
    time_hole = models.TimeField(_("time hole"), default=datetime.time(19,00))
    signup = models.BooleanField(_("signup"), default=False)
            
    name = u"Rep"
    
    def isGig(self): return False
    
    def present(self, request):
        columns = ([],[],[])
        columns[0].append()
    
    class Meta:
        verbose_name = _("rehearsal")
        verbose_name_plural = _('rehearsals')
        app_label = "app"


class Gig(Event):
    name = models.CharField(_("name"), max_length=128)
    time_playing = models.TimeField(_("time playing"), blank=True, null=True)
    
    location = models.CharField(_("location"), max_length=128, blank=True, null=True)
    time_hole = models.TimeField(_("time hole"), blank=True, null=True)
    signup = models.BooleanField(_("signup"), default=True)
    
    public_info = models.TextField(_("public info"), blank=True)
    
    secret = models.BooleanField(_("secret"), default=False)
        
    def isGig(self): return True
    
    class Meta:
        verbose_name = _("gig")
        verbose_name_plural = _('gigs')
        app_label = "app"

class Signup(models.Model):
    objects = InheritanceManager()

    user = models.ForeignKey(User)
    event = models.ForeignKey(Event, editable=False)

    HOLE = 'H'
    DIRECT = 'D'
    NOT_COMING = 'I'
    COMING_CHOICES = (
        (HOLE, u"Till hålan"),
        (DIRECT, u"Direkt"),
        (NOT_COMING, u"Kan inte komma"),
    )
    coming = models.CharField(_("coming"), max_length=1, choices=COMING_CHOICES, default="H")

    car = models.BooleanField(_("can bring car"))
    own_instrument = models.BooleanField(_("brings own instrument"))
    comment = models.CharField(_("comment"), max_length=128, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ("user", "event")
        
        verbose_name = _("signup")
        verbose_name_plural = _('signups')
        app_label = "app"


def get_upcoming_events(user=None):
    events = OrderedDict( (e.pk, e) for e in
        Event.objects.filter(
            date__gte=datetime.date.today())
        .annotate(Count('signup'))
        .select_subclasses())

    # get number coming
    tmp = (Event.objects.filter(pk__in=events.keys())
        .filter(signup__coming__in=[Signup.HOLE, Signup.DIRECT])
        .annotate(num_coming=Count('signup')))
    for e in tmp:
        events[e.pk].num_coming = e.num_coming

    if user is not None:
        # get if user has signed up
        tmp = user.signup_set.filter(
            event_id__in=events.keys())

        for e in events.values():
            e.user_signup = None
        for s in tmp:
            events[s.event_id].user_signup = s

    return events.values()

models.py
#coding: utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from feincms.module.page.models import Page
from django.template.loader import render_to_string

# Templates

Page.register_templates({
    'title': _('Main template'),
    'path': '1col.html',
    'regions': (
        ('main', _('Main content area')),
        ('footer', _('Footer'), 'inherited'),
    ),
})

Page.register_templates({
    'title': _('2 column template'),
    'path': '2col.html',
    'regions': (
        ('col1', _('Column 1')),
        ('col2', _('Column 2')),
        ('footer', _('Footer'), 'inherited'),
    ),
})

# Models

from ak import instrument_choices, section_choices
import datetime
from model_utils.managers import InheritanceManager

class CalendarEntry(models.Model):
    location = models.CharField(max_length=128, blank=True, null=True)
    date = models.DateField()
    time_hole = models.TimeField(blank=True, null=True)
    time_location = models.TimeField(blank=True, null=True)
    signup = models.BooleanField(default=True)
    insiderinfo = models.TextField(blank=True)
    info = models.TextField(blank=True)
    
    objects = InheritanceManager()
    
    class Meta:
        ordering = ["date"]
        app_label = "aksite"
    
    def __unicode__(self):
        return self.location + u" - " + str(self.date)
    
class Rehearsal(CalendarEntry):
    fika = models.CharField(max_length=2, choices=section_choices)
    
    class Meta:
        app_label = "aksite"
    
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('location', u"Hålan")
        kwargs.setdefault('time_hole', datetime.time(19,00))
        kwargs.setdefault('signup', False)
        super(Rehearsal, self).__init__(*args, **kwargs)
        
    def isGig(self): return False

class Gig(CalendarEntry):
    name = models.CharField(max_length=128)
    time_playing = models.TimeField(blank=True, null=True)
    
    class Meta:
        app_label = "aksite"
    
    def __unicode__(self):
        return self.name + u" - " + str(self.date)
        
    def isGig(self): return True

from django.contrib.auth.models import User
class Kamerer(models.Model):
    user = models.ForeignKey(User, unique=True)

    address = models.CharField(max_length=128)
    zip = models.CharField(max_length=5)
    city = models.CharField(max_length=128)
    phone = models.CharField(max_length=16)
    second_phone = models.CharField(max_length=16, blank=True, null=True)
    nation = models.CharField(max_length=128, blank=True, null=True)
    instrument = models.CharField(max_length=2, choices=instrument_choices)
    
    class Meta:
        app_label = "aksite"

# Content types

from feincms.utils import get_object


Page.create_content_type(
    get_object("feincms.content.richtext.models.RichTextContent"))

from feincms.content.medialibrary.models import MediaFileContent
Page.create_content_type(MediaFileContent, POSITION_CHOICES=(
    ('block', _('Block')),
    ('left', _('Left')),
    ('right', _('Right')),
))

from feincms.content.rss.models import RSSContent
Page.create_content_type(RSSContent)

from feincms.content.table.models import TableContent
Page.create_content_type(TableContent)

from feincms.content.template.models import TemplateContent
Page.create_content_type(TemplateContent)

from feincms.content.video.models import VideoContent
Page.create_content_type(VideoContent)

@Page.create_content_type
class AddressRegister(models.Model):
    class Meta:
        abstract = True
        app_label = "aksite"

    def render(self, **kwargs):
        return render_to_string('content/address_register.html', {
            'kamerers': Kamerer.objects.all().order_by("instrument", 
                                                       "user__last_name", 
                                                       "user__first_name"),
        })

Page.register_extensions('datepublisher', 'titles')

templates/1col.html
{% extends "base.html" %}

{% block content %}
{% for content in feincms_page.content.main %}

    {{ content.render() }}
    
{% endfor %}
{% endblock %}

templates/2col.html
{% extends "base.html" %} 

{% block content %}

<div class="col-1" >
{% block column_1 %}
{% for content in feincms_page.content.col1 %}

    {{ content.render() }}
    
{% endfor %}
{% endblock %}
</div>

<div class="col-2" >

{% block column_2 %}
{% for content in feincms_page.content.col2 %}

    {{ content.render() }}
    
{% endfor %}
{% endblock %}

</div>
{% endblock content %}

templates/address_register.html
<div id="instrument-shortcut">
{% for instrument, list in kamerers|groupby("instrument") %}
    <a href="#{{ list[0].get_instrument_display() }}">{{ list[0].get_instrument_display()|capitalize }}</a>{% if not loop.last %}&nbsp;| {% endif %}
{% endfor %}
</div>
<div id="address-register">
{% for instrument, list in kamerers|groupby("instrument") %}
    <h2 id="{{ list[0].get_instrument_display() }}">{{ list[0].get_instrument_display()|capitalize }}</h2>

	{% for kamerer in list %}
    <div class="kamerer">
    <div class="name-email" >
        {{ kamerer.first_name|default }} {{ kamerer.last_name|default }}<br />
        <a href="mailto:{{ kamerer.email }}">{{ kamerer.email }}</a>
    </div>
    <div class="address">
        {{ kamerer.address|default }}<br />
        {{ kamerer.zip|default }} {{ kamerer.city }}
    </div>
    <div class="phone-nation">
        {{ kamerer.nation|default }}
        <a href="tel:{{ kamerer.phone }}">{{ kamerer.phone }}</a><br />
        {% if kamerer.second_phone %}
            <a href="tel:{{ kamerer.second_phone }}">{{ kamerer.second_phone }}</a><br />
        {% endif %}
    </div>
    </div>
	{% endfor %}
{% endfor %}
</div>

templates/base.html
<!doctype html>

<!--[if lt IE 7 ]>
<html lang="en" class="no-js ie6">
<![endif]-->
<!--[if IE 7 ]>
<html lang="en" class="no-js ie7">
<![endif]-->
<!--[if IE 8 ]>
<html lang="en" class="no-js ie8">
<![endif]-->
<!--[if IE 9 ]>
<html lang="en" class="no-js ie9">
<![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">

	<title>
		{% if feincms_page %}
			{{ feincms_page.page_title }} - 
		{% elif self.title().strip() %}
			{{ self.title() }} - 
		{% endif %}
		Alte Kamereren
	</title>
	
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  	<meta name="viewport" content="width=device-width,initial-scale=1">
    
    <meta name="ip" content="{{request.META['REMOTE_ADDR']}}">

    <link rel="stylesheet" href="{{STATIC_URL}}css/style.css?v=2">
    <link rel="stylesheet" href="{{STATIC_URL}}mediaelement/mediaelementplayer.css" />
    
    {% block extra_css %}{% endblock %}

    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>
</head>
<body>
    <a id="af" class="noprint" href="http://www.af.lu.se" style="position: absolute; right: 0; margin: 20px;">
        <img src="/static/images/afny.png">
    </a>
    <div id="container">
        <header class="noprint">
            <div class="user">
                {% if user.is_authenticated() %}
                    <a href="/users/profile">profil</a> | <a href="/users/logout">logga ut</a>
                    {% if user.is_staff %}| <a href="/admin">admin</a>{% endif %}
                {% else %}
                    <a href="/users/login?next={% block next_after_login %}{{ request.get_full_path() }}{% endblock %}">
                    	logga in
                   	</a>
                {% endif %}
            </div>
            <div class="ak-logo">
                <a href="/"><img src="{{ STATIC_URL }}images/ak_logo.png" alt="altekamererens logo" /></a>
            </div>
            {% for p, s in navigation(request) %}
            	{% if loop.first %}
            		<ul class="nav" id="main-nav">
            			<li>
            	{% elif s.new_level %}
            		<ul>
            			<li>
            	{% else %}
	            		</li>
	            		<li>
            	{% endif %}
            		<a href="{{ p.get_absolute_url() }}"
            		{% if feincms_page and is_equal_or_parent_of(p, feincms_page) %} 
            			class="active"
            		{% endif %}>
            			{{ p.title }}
            		</a>
            	{% for level in s.closed_levels %}
            			</li>
            		</ul>
            	{% endfor %}
            {% endfor %}
            </ul>
        </header>

        <div id="main" class="clearfix" role="main">
            {% block content_header %}
                {% if error %}<div class="error">{{ error }}</div>{% endif %}
                {% if info %}<div class="info">{{ info }}</div>{% endif %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="info">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endblock %}
            <h1>
	            {% block title %}
	            	{% if feincms_page %}
	            		{{ feincms_page.content_title }}
	            	{% endif %}
	            {% endblock %}
            </h1>
            {% block content %}
            {% endblock %}
        </div>

        <footer>
            {% block footer_content%}
                {% if feincms_page %}
                    {% for content in feincms_page.content.footer %}
                        <div class="block">
                            {{ content.render() }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}
        </footer>
        
    </div>
    
    <!-- JavaScript at the bottom for fast page loading -->
    
    <script src="{{ JQUERY_URL }}"></script>

    <script src="{{ STATIC_URL }}mediaelement/mediaelement-and-player.min.js"></script>
    <script src="{{ STATIC_URL }}js/plugins.js"></script>
    <script src="{{ STATIC_URL }}js/script.js"></script>
    
    {% block extra_script %}{% endblock %}
    
    {% if not user.is_authenticated() %}
    <!-- Google Analytics (only for non members) -->
	<script>
	  window._gaq = [['_setAccount','UA-27394459-1'],['_trackPageview'],['_trackPageLoadTime']];
	  Modernizr.load({
	    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
	  });
	</script>
	{% endif %}
	
	<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
      chromium.org/developers/how-tos/chrome-frame-getting-started -->
	<!--[if lt IE 7 ]>
	  <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
	  <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
	<![endif]-->
</body>
</html>

templates/gigs.html
<dl class="gigs">
{% for event in events %}
    {% if not event.secret %}
        <dt>{{ event.name }}, {{ event.location }}</dt>
        <dd>
            <span class="datetime">
                {{ event.date|date("l d/m Y")}}
                {% if event.time_playing %}
                    {{event.time_playing|time }}
                {% endif %}
            </span><br>
           {% if event.public_info %}{{ event.public_info }}{% endif %}
        </dd>
    {% endif %}
{% endfor %}
</dl>

templates/special.html
{% extends "base.html" %}

{% block content %}
{% for content in feincms_page.content.special %}

    {{ content.render(request=request, user=user) }}
    
{% endfor %}
{% endblock %}

templates/upcoming.html
<div id="upcoming">
{% for year, list in events|groupby("date.year") %}
    <h2>{{ year }}</h2>
    {% for month, list in list|groupby("date.month") %}
        <h2>{{ list[0].date|date("F")}}</h2>
            
        {% for event in list %}
            <div id="event_{{ event.pk }}" class="cell" style="clear: both; font-weight: bold;">
                <p>{{ event.date|date("l d/m")}}</p>
            {% if event.isGig() %}
                <p>{{ event.name }}</p>
            {% else %}
                <p>Rep</p>
            {% endif %}
            {% if event.location %}
                <p>{{ event.location }}</p>
            {% endif %}
            </div>
            <div class="cell" >
            {% if event.time_hole %}
                <p>Samling i hålan {{ event.time_hole|time }}</p>
            {% endif %}
            {% if event.time_location %}
                <p>Samling på plats {{ event.time_location|time }}</p>
            {% endif %}
            {% if event.isGig() and event.time_playing %}
                <p>Spelning börjar {{ event.time_playing|time }}</p>
            {% endif %}
            </div>
            <div class="cell" >
            {% if not event.isGig() %}
                <p>Fika och städning: {{ event.get_fika_display() }}</p>
            {% endif %}
            {% if user.is_authenticated() and user.is_active and event.signup %}
                {% set signup = event.get_signup(user) %}
                {% if signup %}
                    <p><a href="/event/signup/{{event.pk}}" style="color: #00cc00;">
                        Anmäld: {{ signup.get_coming_display() }}
                    </a></p>
                {% else %}
                    <p><a href="/event/signup/{{event.pk}}">Anmäl</a></p>
                {% endif %}
                <p>Kommer: {{ event.get_coming() }} Anmälda: {{ event.get_signed_up() }}</p>
            {% endif %}
            </div>
            <div style="clear: both;">
                {% if event.info and event.info != "<br />" %}
                    {{event.info}}
                {% endif %}
            </div>
            <hr>
        {% endfor %}
        
    {% endfor %}
{% endfor %}
</div>